### ISSUE TITLE
Demo gives wrong answer!

### ISSUE THREAD

**Issue by didamarkovic** [didamarkovic/globygon#7]
The final plot of the Demo notebook gives the wrong answer. It looks as if the Cartesian Center of Mass is converted to Ra//Dec incorrectly, but it should be.
![wrong](https://user-images.githubusercontent.com/9950748/123354184-f7020180-d517-11eb-9508-01122aa126b4.png)

**Comment by decaelus** [comment]
Can you post the code you used to create this plot?

**Comment by didamarkovic** [comment]
> Can you post the code you used to create this plot?

It's the last plot here: https://github.com/didamarkovic/globygon/blob/makedemo/Demo.ipynb.

**Comment by didamarkovic** [comment]
This is not a bug. It is correct. Just remember when looking at this plot that circle of equal declination IS NOT a great circle!

**Comment by didamarkovic** [comment]
If really keen, could test on two points against something like the `midpoint` function from [here](https://pypi.org/project/great-circle-calculator/).
